attribute_means:
  area_gages2: 386.25394957983195
  pet_mean: 2.4810957677198178
  runoff_ratio: 0.43053148688330506
  soil_depth_statsgo: 1.2850626638802924
attribute_stds:
  area_gages2: 527.6328781039924
  pet_mean: 0.3213507846110617
  runoff_ratio: 0.115097962976939
  soil_depth_statsgo: 0.24402404707950368
xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    PRCP(mm/day)_maurer:
      dims: []
      attrs: {}
      data: 6.491489887237549
    PRCP(mm/day)_nldas:
      dims: []
      attrs: {}
      data: 7.619146823883057
    QObs(mm/d):
      dims: []
      attrs: {}
      data: 2.544370412826538
    prcp(mm/day)_daymet:
      dims: []
      attrs: {}
      data: 7.729273796081543
    srad(W/m2)_daymet:
      dims: []
      attrs: {}
      data: 123.22931671142578
    tmax(C)_daymet:
      dims: []
      attrs: {}
      data: 10.687082290649414
    tmin(C)_daymet:
      dims: []
      attrs: {}
      data: 9.913265228271484
    vp(Pa)_daymet:
      dims: []
      attrs: {}
      data: 605.6192016601562
    frac_low:
      dims: []
      attrs: {}
      data: 0.00031569190017089664
    frac_moderate:
      dims: []
      attrs: {}
      data: 9.995068589650573e-05
    frac_high:
      dims: []
      attrs: {}
      data: 2.8915697297717868e-05
    frac_inc_greenness:
      dims: []
      attrs: {}
      data: 9.432735807218243e-06
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    PRCP(mm/day)_maurer:
      dims: []
      attrs: {}
      data: 3.189729928970337
    PRCP(mm/day)_nldas:
      dims: []
      attrs: {}
      data: 3.148333787918091
    QObs(mm/d):
      dims: []
      attrs: {}
      data: 1.487260341644287
    prcp(mm/day)_daymet:
      dims: []
      attrs: {}
      data: 3.421461820602417
    srad(W/m2)_daymet:
      dims: []
      attrs: {}
      data: 324.99127197265625
    tmax(C)_daymet:
      dims: []
      attrs: {}
      data: 15.738828659057617
    tmin(C)_daymet:
      dims: []
      attrs: {}
      data: 3.92391300201416
    vp(Pa)_daymet:
      dims: []
      attrs: {}
      data: 976.1524047851562
    frac_low:
      dims: []
      attrs: {}
      data: 7.2679272807005905e-06
    frac_moderate:
      dims: []
      attrs: {}
      data: 1.9687781068335504e-06
    frac_high:
      dims: []
      attrs: {}
      data: 4.993081166227242e-07
    frac_inc_greenness:
      dims: []
      attrs: {}
      data: 1.4537806784249976e-07
